

experiment:
  random_seed: 13
  exp_name: "${experiment.task}-${experiment.dataset}-${experiment.input_format}-${experiment.symrep}"
  epoch: 300
  batch_size: 32
  lr: 5e-3
  lr_gamma: 0.99
  es_patience: 50     # early stopping patience
  es_threshold: 0.005  # early stopping threshold 
  
  restore_training: False
  device: [3, 5]
  continue_training: False
  checkpoint_dir: "checkpoints/${experiment.exp_name}"
  checkpoint_file: "${experiment.checkpoint_dir}/epoch=49-step=1850.ckpt"

  load_data: True # Weather load existing data
  feat_level: 0 # controls the amount of information for more standardized comparison. 0 for the basic, 1 for basic+extra 

  dataset: ASAP  # ASAP or ATEPP
  task: difficulty_id  # composer_id, performer_id, difficulty_id
  input_format: musicxml  # perfmidi, musicxml, kern
  symrep: graph # matrix, sequence, graph
  emb_dim: 32 # frontend embedding from each segment
  test_split_size: 0.2

segmentation:    # determine how the entire piece is segmented into local clips
  seg_type: fix_time  # fix_num, fix_size, fix_time
  seg_num: 4   # number of segments if seg_type==fix_nums
  seg_size: 300 # The V size of subgraph to sample if seg_type==fix_size. Also for 
  seg_time: 60 # in seconds if seg_type==fix_time. 
  seg_beat: 180 # in beats if seg_type==fix_time

# Representation
matrix:
  resolution: 800 # the width of matrix
  bins: 131 # 128 pitchs + 3 pedals
  n_channels: 2 # n channels of matrix. onset roll + frame roll (perfmidi: velocity, musicxml: voice)


sequence:
  mid_encoding: MIDILike # MIDILike, REMI
  pr_start: 21 
  pr_end: 109
  beat_res: 8  # 
  nb_velocities: 32
  max_seq_len: 1600 # max length ATEPP: 20000, ASAP: 18000
  BPE: False # not implemented

graph:
  basic_edges: ['onset', 'consecutive', 'sustain', 'silence', 
      'consecutive_rev', 'sustain_rev', 'silence_rev'
      ]
  mid_window: 0.03 # window for determine whether notes are same onset, consecutive and sustain
  save_dir: "/homes/hz009/Research/SymRep/assets/${experiment.dataset}/${experiment.input_format}"

# DATASET 
dataset:
  ASAP:
    dataset_dir: /homes/hz009/Research/Datasets/asap-dataset/
    metadata_file: /homes/hz009/Research/Datasets/asap-dataset/metadata-v1.2.csv

  ATEPP: 
    dataset_dir: /homes/hz009/Research/Datasets/ATEPP-1.1/
    metadata_file: /homes/hz009/Research/Datasets/ATEPP-1.1/ATEPP-metadata-1.3.csv

  PD:
    dataset_dir: /homes/hz009/Research/Datasets/piano_difficulty/
    metadata_file: /homes/hz009/Research/Datasets/piano_difficulty/labels.csv

# HYDRA
defaults:  
  - _self_  
  # - override hydra/hydra_logging: disabled  
  # - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .