

experiment:
  exp_name: "${experiment.task}-${experiment.dataset}-${experiment.input_format}-${experiment.symrep}"
  epoch: 300
  batch_size: 8
  lr: 1e-4
  restore_training: False
  device: 4
  continue_training: False
  checkpoint_dir: "checkpoints/${experiment.exp_name}"
  checkpoint_file: "${experiment.checkpoint_dir}/epoch=49-step=1850.ckpt"

  n_segs: 4
  dataset: ATEPP
  task: composer_id 
  input_format: perfmidi # perfmidi, musicxml, kern
  symrep: sequence # matrix, sequence, graph
  emb_dim: 32 # frontend embedding from each segment


# TASK
# composer_id


# Representation
matrix:
  resolution: 800 # the width of matrix
  bins: 131 # 128 pitchs + 3 pedals
  n_channels: 2 # n channels of matrix. onset roll + frame roll (perfmidi: velocity, musicxml: voice)

sequence:
  pr_start: 21 
  pr_end: 109
  beat_res: 8  # 
  nb_velocities: 32
  seq_len: 20000 # should think about how to get variable length for segments


# DATASET 
dataset:
  ASAP:
    dataset_dir: /homes/hz009/Research/Datasets/asap-dataset/
    metadata_file: /homes/hz009/Research/Datasets/asap-dataset/metadata-v1.0.csv

  ATEPP: 
    dataset_dir: /homes/hz009/Research/Datasets/ATEPP-1.1/
    metadata_file: /homes/hz009/Research/Datasets/ATEPP-1.1/ATEPP-metadata-1.3.csv

  PD:
    dataset_dir: /homes/hz009/Research/Datasets/piano_difficulty/
    metadata_file: /homes/hz009/Research/Datasets/piano_difficulty/labels.csv

# HYDRA
defaults:  
  - _self_  
  # - override hydra/hydra_logging: disabled  
  # - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .