

experiment:
  random_seed: 13
  exp_name: "${experiment.task}-${experiment.dataset}-${experiment.input_format}-${experiment.symrep}"
  epoch: 300
  batch_size: 2
  lr: 1e-5
  restore_training: False
  device: [4]
  continue_training: False
  checkpoint_dir: "checkpoints/${experiment.exp_name}"
  checkpoint_file: "${experiment.checkpoint_dir}/epoch=49-step=1850.ckpt"

  feat_level: 0 # controls the amount of information for more standardized comparison. 0 for the basic, 1 for basic+extra 

  n_segs: null   # if null, will use varied number of segments, determined by piece length and rep parameters
  dataset: ATEPP  # ASAP or ATEPP
  task: performer_id  # composer_id, performer_id
  input_format: perfmidi  # perfmidi, musicxml, kern
  symrep: graph # matrix, sequence, graph
  emb_dim: 32 # frontend embedding from each segment


# Representation
matrix:
  resolution: 800 # the width of matrix
  bins: 131 # 128 pitchs + 3 pedals
  n_channels: 2 # n channels of matrix. onset roll + frame roll (perfmidi: velocity, musicxml: voice)
  fix_seg_sec: 60 # n
  fix_seg_beats: 120 #

sequence:
  mid_encoding: MIDILike # MIDILike, REMI
  pr_start: 21 
  pr_end: 109
  beat_res: 8  # 
  nb_velocities: 32
  seq_len: 1600 # max length ATEPP: 20000, ASAP: 18000
  BPE: False # not implemented

graph:
  basic_edges: ['onset', 'consecutive', 'sustain', 'silence']
  mid_window: 0.05 # window for determine whether notes are same onset, consecutive and sustain
  subgraph_size: 300 # The V size of subgraph to sample. active if cfg.experiment.n_segs == null. 
  save_dir: "/homes/hz009/Research/SymRep/assets/${experiment.dataset}/${experiment.input_format}"

# DATASET 
dataset:
  ASAP:
    dataset_dir: /homes/hz009/Research/Datasets/asap-dataset/
    metadata_file: /homes/hz009/Research/Datasets/asap-dataset/metadata-v1.1.csv

  ATEPP: 
    dataset_dir: /homes/hz009/Research/Datasets/ATEPP-1.1/
    metadata_file: /homes/hz009/Research/Datasets/ATEPP-1.1/ATEPP-metadata-1.3.csv

  PD:
    dataset_dir: /homes/hz009/Research/Datasets/piano_difficulty/
    metadata_file: /homes/hz009/Research/Datasets/piano_difficulty/labels.csv

# HYDRA
defaults:  
  - _self_  
  # - override hydra/hydra_logging: disabled  
  # - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .